services:
  mysql:
    image: mysql:latest
    container_name: mysql_treeqlqs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    #ports:
    #  - "3306:3306"
    networks:
      - php-api-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm_treeqlqs
    volumes:
      - ./php:/var/www/html
    environment:
      PHP_CRUD_API_PORT: 3306  #${PORT}
      PHP_CRUD_API_ADDRESS: mysql_treeqlqs  #${SERVER_NAME}
      PHP_CRUD_API_DATABASE: ${MYSQL_DATABASE}
      PHP_CRUD_API_USERNAME: ${MYSQL_USER}
      PHP_CRUD_API_PASSWORD: ${MYSQL_PASSWORD}
      PHP_CRUD_API_DEBUG: ${PHP_CRUD_API_DEBUG}
    depends_on:
      - mysql
    networks:
      - php-api-network

  web:
    image: nginx:latest
    container_name: nginx_treeqlqs
    restart: always
    environment:
      SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./php:/var/www/html
    ports:
      - "${PORT}:80"
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
    networks:
      - php-api-network

  #adminer:
  #  container_name: dbadmin_treeqlqs
  #  image: adminer
  #  restart: always
  #  environment:
  #    ADMINER_DEFAULT_SERVER: mysql_treeqlqs
  #  networks:
  #    - php-api-network
  #  depends_on:
  #    - web

  phpmyadmin:
    container_name: dbadmin_treeqlqs
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_treeqlqs
      PMA_ABSOLUTE_URI: ${SERVER_NAME}dbadmin/
    networks:
      - php-api-network
    depends_on:
      - web

  swagger:
    container_name: swagger_treeqlqs
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: ${SERVER_NAME}openapi
      DOC_EXPANSION: none
    networks:
      - php-api-network
    depends_on:
      - web

networks:
  php-api-network:
    driver: bridge