services:
  mysql:
    image: mysql:latest
    container_name: mysql_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - php-api-network
    profiles:
      - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:latest
    container_name: postgres_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - php-api-network
    profiles:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    restart: always
    environment:
      PHP_CRUD_API_DRIVER: ${PHP_CRUD_API_DRIVER}
      PHP_CRUD_API_PORT: ${PHP_CRUD_API_PORT}
      PHP_CRUD_API_ADDRESS: ${PHP_CRUD_API_ADDRESS}
      PHP_CRUD_API_DATABASE: ${PHP_CRUD_API_DATABASE}
      PHP_CRUD_API_USERNAME: ${PHP_CRUD_API_USERNAME}
      PHP_CRUD_API_PASSWORD: ${PHP_CRUD_API_PASSWORD}
      PHP_CRUD_API_DEBUG: ${PHP_CRUD_API_DEBUG}
      CONTAINERS_NAME_SUFFIX: ${CONTAINERS_NAME_SUFFIX}
    ports:
      - "${PORT}:80"
    entrypoint: /entrypoint.sh
    networks:
      - php-api-network

  adminer:
    container_name: dbadmin_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
    networks:
      - php-api-network
    depends_on:
      - php
    profiles:
      - adminer

  phpmyadmin:
    container_name: phpmyadmin_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_treeqlqs-${CONTAINERS_NAME_SUFFIX}
      PMA_ABSOLUTE_URI: ${SERVER_NAME}dbadmin/
    networks:
      - php-api-network
    depends_on:
      - php
    profiles:
      - phpmyadmin

  swagger:
    container_name: swagger_treeqlqs-${CONTAINERS_NAME_SUFFIX}
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON_URL: ${SERVER_NAME}openapi
      DOC_EXPANSION: none
    networks:
      - php-api-network
    depends_on:
      - php

networks:
  php-api-network:
    driver: bridge